"""Pydantic models for the Macroscope SEO content pipeline.

These schemas define the data contracts between all pipeline stages.
Every agent input and output must conform to these models.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from enum import Enum
from typing import Annotated, Optional

from pydantic import BaseModel, Field, computed_field, field_validator


class SearchIntent(str, Enum):
    """Classification of user search intent."""

    INFORMATIONAL = "informational"
    NAVIGATIONAL = "navigational"
    TRANSACTIONAL = "transactional"
    COMMERCIAL = "commercial"


class PipelineStage(str, Enum):
    """Named pipeline stages for tracking and artifact mapping."""

    COLLECT_SIGNALS = "collect_signals"
    GENERATE_TOPICS = "generate_topics"
    SCORE_TOPICS = "score_topics"
    BUILD_BRIEF = "build_brief"
    WRITE_DRAFT = "write_draft"
    QA_OPTIMIZE = "qa_optimize"
    EXPORT = "export"
    PERSIST_HISTORY = "persist_history"


class FailureCategory(str, Enum):
    """Categorized failure types for structured error handling."""

    VALIDATION_ERROR = "validation_error"
    PROVIDER_ERROR = "provider_error"
    SCORING_REJECTION = "scoring_rejection"
    QA_FAILURE = "qa_failure"
    IO_ERROR = "io_error"
    TIMEOUT = "timeout"
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# Topic candidates
# ---------------------------------------------------------------------------


class TopicCandidate(BaseModel):
    """A proposed blog topic generated by the topic researcher."""

    title: str = Field(..., min_length=10, max_length=200)
    slug: str = Field(..., pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
    cluster: str = Field(..., description="Topic cluster from topic_clusters.yaml")
    description: str = Field(..., min_length=20)
    target_keywords: list[str] = Field(..., min_length=2)
    search_intent: SearchIntent
    freshness_signal: Optional[str] = None
    source: str = Field(..., description="Agent or signal that generated this candidate")
    rationale: str = Field(..., min_length=10)

    @field_validator("target_keywords")
    @classmethod
    def keywords_are_lowercase(cls, v: list[str]) -> list[str]:
        return [kw.lower().strip() for kw in v]

    @field_validator("slug")
    @classmethod
    def slug_is_normalized(cls, v: str) -> str:
        return v.lower().strip()


# ---------------------------------------------------------------------------
# Market signals
# ---------------------------------------------------------------------------


class MarketSignal(BaseModel):
    """A single signal from market/social/news monitoring."""

    source: str
    title: str
    url: Optional[str] = None
    summary: str = Field(..., min_length=10)
    relevance_score: float = Field(..., ge=0.0, le=1.0)
    detected_at: datetime
    themes: list[str] = Field(..., min_length=1)


class MarketSignalReport(BaseModel):
    """Aggregated market intelligence report."""

    signals: list[MarketSignal]
    trending_themes: list[str]
    recommended_angles: list[str]
    collected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @field_validator("trending_themes")
    @classmethod
    def dedupe_themes(cls, v: list[str]) -> list[str]:
        seen: set[str] = set()
        result: list[str] = []
        for t in v:
            key = t.lower().strip()
            if key not in seen:
                seen.add(key)
                result.append(t)
        return result


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------


class TopicScore(BaseModel):
    """Weighted scoring for a topic candidate.

    Weights: business_relevance=25, search_opportunity=20, aeo_fit=15,
    freshness=10, authority_to_win=15, uniqueness_vs_archive=10, production_ease=5.
    Total possible: 100.
    """

    business_relevance: float = Field(..., ge=0.0, le=25.0)
    search_opportunity: float = Field(..., ge=0.0, le=20.0)
    aeo_fit: float = Field(..., ge=0.0, le=15.0)
    freshness: float = Field(..., ge=0.0, le=10.0)
    authority_to_win: float = Field(..., ge=0.0, le=15.0)
    uniqueness_vs_archive: float = Field(..., ge=0.0, le=10.0)
    production_ease: float = Field(..., ge=0.0, le=5.0)

    @computed_field
    @property
    def total(self) -> float:
        """Sum of all scoring dimensions."""
        return round(
            self.business_relevance
            + self.search_opportunity
            + self.aeo_fit
            + self.freshness
            + self.authority_to_win
            + self.uniqueness_vs_archive
            + self.production_ease,
            2,
        )


class ScoredTopic(BaseModel):
    """A topic candidate with its score and selection status."""

    candidate: TopicCandidate
    score: TopicScore
    rejection_reasons: list[str] = Field(default_factory=list)
    selected: bool = False

    @computed_field
    @property
    def total_score(self) -> float:
        """Convenience accessor for the topic's total score."""
        return self.score.total


# ---------------------------------------------------------------------------
# Research brief
# ---------------------------------------------------------------------------


class OutlineSection(BaseModel):
    """A section in the article outline."""

    heading: str = Field(..., min_length=2)
    description: str = Field(..., min_length=5)
    target_word_count: int = Field(default=200, ge=50, le=1500)
    key_points: list[str] = Field(default_factory=list)


class FAQ(BaseModel):
    """A frequently asked question with suggested answer."""

    question: str = Field(..., min_length=10)
    suggested_answer: str = Field(..., min_length=20)


class InternalLink(BaseModel):
    """A suggested internal link to existing Macroscope content."""

    anchor_text: str
    target_path: str = Field(..., description="Relative URL path on macroscope.com")
    context: str = Field(..., description="Where/how to place this link in the article")


class ResearchBrief(BaseModel):
    """Comprehensive research brief for blog writing.

    Contains everything a writer needs to produce the article
    without additional research.
    """

    topic: TopicCandidate
    outline: list[OutlineSection] = Field(..., min_length=3)
    target_word_count: int = Field(default=2000, ge=800, le=5000)
    primary_keyword: str
    secondary_keywords: list[str] = Field(..., min_length=2)
    entities: list[str] = Field(..., min_length=1, description="People, companies, tools, concepts")
    faqs: list[FAQ] = Field(..., min_length=4)
    claims_needing_evidence: list[str]
    internal_link_suggestions: list[InternalLink]
    cta: str = Field(..., min_length=5)
    do_not_say: list[str] = Field(..., min_length=1)
    meta_description: str = Field(..., min_length=50, max_length=160)
    title_options: list[str] = Field(..., min_length=2)

    @field_validator("primary_keyword")
    @classmethod
    def keyword_normalized(cls, v: str) -> str:
        return v.lower().strip()

    def brief_hash(self) -> str:
        """SHA-256 prefix for traceability."""
        return hashlib.sha256(self.model_dump_json().encode()).hexdigest()[:12]


# ---------------------------------------------------------------------------
# Articles
# ---------------------------------------------------------------------------


class DraftArticle(BaseModel):
    """First draft of the blog article."""

    title: str
    slug: str = Field(..., pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
    content_md: str = Field(..., min_length=100)
    word_count: int = Field(..., ge=1)
    brief_hash: str = Field(..., description="SHA-256 prefix of the serialized brief")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SEOAEOScore(BaseModel):
    """SEO and AEO quality scores (each dimension 0-10, total 0-100)."""

    title_score: float = Field(..., ge=0.0, le=10.0)
    meta_description_score: float = Field(..., ge=0.0, le=10.0)
    keyword_density_score: float = Field(..., ge=0.0, le=10.0)
    heading_structure_score: float = Field(..., ge=0.0, le=10.0)
    internal_links_score: float = Field(..., ge=0.0, le=10.0)
    faq_presence_score: float = Field(..., ge=0.0, le=10.0)
    direct_answer_score: float = Field(..., ge=0.0, le=10.0)
    readability_score: float = Field(..., ge=0.0, le=10.0)
    content_depth_score: float = Field(..., ge=0.0, le=10.0)
    freshness_signals_score: float = Field(..., ge=0.0, le=10.0)

    @computed_field
    @property
    def total(self) -> float:
        """Sum of all SEO/AEO dimensions (0-100)."""
        return round(
            self.title_score
            + self.meta_description_score
            + self.keyword_density_score
            + self.heading_structure_score
            + self.internal_links_score
            + self.faq_presence_score
            + self.direct_answer_score
            + self.readability_score
            + self.content_depth_score
            + self.freshness_signals_score,
            2,
        )

    @computed_field
    @property
    def normalized(self) -> float:
        """Normalized score (0.0-1.0)."""
        return round(self.total / 100.0, 4)

    @computed_field
    @property
    def grade(self) -> str:
        """Letter grade: A (>=80), B (>=65), C (>=50), D (>=35), F (<35)."""
        t = self.total
        if t >= 80:
            return "A"
        if t >= 65:
            return "B"
        if t >= 50:
            return "C"
        if t >= 35:
            return "D"
        return "F"


class FinalArticle(BaseModel):
    """The final, QA-passed article ready for publishing."""

    title: str
    slug: str = Field(..., pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
    content_md: str = Field(..., min_length=100)
    meta_description: str = Field(..., min_length=50, max_length=160)
    word_count: int = Field(..., ge=1)
    seo_aeo_score: SEOAEOScore
    faqs_present: bool
    internal_links: list[str]
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# Run tracking
# ---------------------------------------------------------------------------


class StageResult(BaseModel):
    """Result of a single pipeline stage execution."""

    stage: str
    success: bool
    duration_seconds: float = Field(..., ge=0.0)
    error: Optional[str] = None
    failure_category: Optional[FailureCategory] = None
    artifact_path: Optional[str] = None


class RunSummary(BaseModel):
    """Summary of a complete pipeline run."""

    run_id: str
    started_at: datetime
    completed_at: Optional[datetime] = None
    stages: list[StageResult] = Field(default_factory=list)
    topic_selected: Optional[str] = None
    final_score: Optional[float] = None
    final_grade: Optional[str] = None
    word_count: Optional[int] = None
    artifacts: dict[str, str] = Field(
        default_factory=dict, description="stage_name -> artifact file path"
    )
    errors: list[str] = Field(default_factory=list)

    @computed_field
    @property
    def success(self) -> bool:
        """Whether the run completed without errors."""
        return len(self.errors) == 0 and self.completed_at is not None

    @computed_field
    @property
    def total_duration_seconds(self) -> float:
        """Total wall-clock time of the run."""
        if self.started_at and self.completed_at:
            return round((self.completed_at - self.started_at).total_seconds(), 2)
        return sum(s.duration_seconds for s in self.stages)

    @computed_field
    @property
    def stages_completed(self) -> list[str]:
        """Names of stages that completed successfully."""
        return [s.stage for s in self.stages if s.success]

    @computed_field
    @property
    def stages_failed(self) -> list[str]:
        """Names of stages that failed."""
        return [s.stage for s in self.stages if not s.success]

    def to_concise_json(self) -> dict:
        """Return a CI-friendly concise summary dict."""
        return {
            "run_id": self.run_id,
            "success": self.success,
            "topic": self.topic_selected,
            "score": self.final_score,
            "grade": self.final_grade,
            "word_count": self.word_count,
            "duration_seconds": self.total_duration_seconds,
            "stages_completed": self.stages_completed,
            "stages_failed": self.stages_failed,
            "error_count": len(self.errors),
            "errors": self.errors[:5],
        }
