"""Pydantic models for the Macroscope SEO content pipeline.

These schemas define the data contracts between all pipeline stages.
Every agent input and output must conform to these models.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from enum import Enum
from typing import Annotated, Any, Optional

from pydantic import BaseModel, Field, computed_field, field_validator


class SearchIntent(str, Enum):
    """Classification of user search intent."""

    INFORMATIONAL = "informational"
    NAVIGATIONAL = "navigational"
    TRANSACTIONAL = "transactional"
    COMMERCIAL = "commercial"


class PipelineStage(str, Enum):
    """Named pipeline stages for tracking and artifact mapping."""

    BOOTSTRAP_RUN = "bootstrap_run"
    COLLECT_SIGNALS = "collect_signals"
    GENERATE_TOPICS = "generate_topics"
    SCORE_TOPICS = "score_topics"
    BUILD_BRIEF = "build_brief"
    WRITE_DRAFT = "write_draft"
    QA_OPTIMIZE = "qa_optimize"
    FACT_CHECK = "fact_check"
    EXPORT = "export"
    PERSIST_HISTORY = "persist_history"


class FailureCategory(str, Enum):
    """Categorized failure types for structured error handling."""

    VALIDATION_ERROR = "validation_error"
    PROVIDER_ERROR = "provider_error"
    SCORING_REJECTION = "scoring_rejection"
    QA_FAILURE = "qa_failure"
    IO_ERROR = "io_error"
    TIMEOUT = "timeout"
    CANCELED = "canceled"
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# Run context and execution policies
# ---------------------------------------------------------------------------


class QualityPolicy(BaseModel):
    """Quality and retry thresholds for a single run."""

    min_topic_consensus_score: float = Field(default=7.2, ge=0.0, le=10.0)
    min_topic_authority_score: float = Field(default=7.5, ge=0.0, le=10.0)
    min_brief_quality_score: float = Field(default=8.0, ge=0.0, le=10.0)
    min_draft_quality_score: float = Field(default=8.2, ge=0.0, le=10.0)
    final_average_score: float = Field(default=9.0, ge=0.0, le=10.0)
    final_min_judge_score: float = Field(default=8.0, ge=0.0, le=10.0)
    final_technical_accuracy_score: float = Field(default=9.0, ge=0.0, le=10.0)
    topic_judge_spread_threshold: float = Field(default=1.5, ge=0.0, le=10.0)
    topic_judge_variance_threshold: float = Field(default=0.7, ge=0.0, le=10.0)
    draft_judge_spread_threshold: float = Field(default=1.4, ge=0.0, le=10.0)
    draft_judge_variance_threshold: float = Field(default=0.6, ge=0.0, le=10.0)
    final_judge_spread_threshold: float = Field(default=1.2, ge=0.0, le=10.0)
    final_judge_variance_threshold: float = Field(default=0.45, ge=0.0, le=10.0)
    max_research_retries: int = Field(default=1, ge=0, le=5)
    max_brief_retries: int = Field(default=1, ge=0, le=5)
    max_optimization_rounds: int = Field(default=0, ge=0)


class SourcePolicy(BaseModel):
    """Required source coverage for technically credible research."""

    required_source_classes: list[str] = Field(default_factory=list)
    minimum_unique_classes: int = Field(default=3, ge=1, le=10)
    require_primary_technical_source: bool = True
    lookback_days: int = Field(default=14, ge=1, le=90)


class RunContext(BaseModel):
    """Immutable run-scoped execution context."""

    run_id: str
    run_started_at: datetime
    provider_mode: str
    config_snapshot: dict[str, Any] = Field(default_factory=dict)
    quality_policy: QualityPolicy
    source_policy: SourcePolicy
    agent_manifest: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Topic candidates
# ---------------------------------------------------------------------------


class TopicCandidate(BaseModel):
    """A proposed blog topic generated by the topic researcher."""

    title: str = Field(..., min_length=10, max_length=200)
    slug: str = Field(..., pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
    cluster: str = Field(..., description="Topic cluster from topic_clusters.yaml")
    description: str = Field(..., min_length=20)
    target_keywords: list[str] = Field(..., min_length=2)
    search_intent: SearchIntent
    freshness_signal: Optional[str] = None
    source: str = Field(..., description="Agent or signal that generated this candidate")
    rationale: str = Field(..., min_length=10)

    @field_validator("target_keywords")
    @classmethod
    def keywords_are_lowercase(cls, v: list[str]) -> list[str]:
        return [kw.lower().strip() for kw in v]

    @field_validator("slug")
    @classmethod
    def slug_is_normalized(cls, v: str) -> str:
        return v.lower().strip()


# ---------------------------------------------------------------------------
# Market signals
# ---------------------------------------------------------------------------


class MarketSignal(BaseModel):
    """A single signal from market/social/news monitoring."""

    source: str
    title: str
    url: Optional[str] = None
    summary: str = Field(..., min_length=10)
    relevance_score: float = Field(..., ge=0.0, le=1.0)
    detected_at: datetime
    themes: list[str] = Field(..., min_length=1)


class MarketSignalReport(BaseModel):
    """Aggregated market intelligence report."""

    signals: list[MarketSignal]
    trending_themes: list[str]
    recommended_angles: list[str]
    collected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @field_validator("trending_themes")
    @classmethod
    def dedupe_themes(cls, v: list[str]) -> list[str]:
        seen: set[str] = set()
        result: list[str] = []
        for t in v:
            key = t.lower().strip()
            if key not in seen:
                seen.add(key)
                result.append(t)
        return result


class CanonicalSource(BaseModel):
    """Normalized source reference used in the research packet."""

    source_class: str
    title: str
    url: Optional[str] = None
    note: str = ""


class ResearchFact(BaseModel):
    """Compact normalized fact extracted from research."""

    statement: str = Field(..., min_length=10)
    source_class: str
    evidence_titles: list[str] = Field(default_factory=list)
    freshness_note: Optional[str] = None


class ResearchPacket(BaseModel):
    """Structured, reusable research artifact for downstream stages."""

    themes: list[str] = Field(default_factory=list)
    normalized_facts: list[ResearchFact] = Field(default_factory=list)
    canonical_sources: list[CanonicalSource] = Field(default_factory=list)
    fresh_market_notes: list[str] = Field(default_factory=list)
    keyword_serp_notes: list[str] = Field(default_factory=list)
    source_coverage: Optional["SourceCoverageReport"] = None
    collected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------


class TopicScore(BaseModel):
    """Weighted scoring for a topic candidate.

    Weights: business_relevance=25, search_opportunity=20, aeo_fit=15,
    freshness=10, authority_to_win=15, uniqueness_vs_archive=10, production_ease=5.
    Total possible: 100.
    """

    business_relevance: float = Field(..., ge=0.0, le=25.0)
    search_opportunity: float = Field(..., ge=0.0, le=20.0)
    aeo_fit: float = Field(..., ge=0.0, le=15.0)
    freshness: float = Field(..., ge=0.0, le=10.0)
    authority_to_win: float = Field(..., ge=0.0, le=15.0)
    uniqueness_vs_archive: float = Field(..., ge=0.0, le=10.0)
    production_ease: float = Field(..., ge=0.0, le=5.0)

    @computed_field
    @property
    def total(self) -> float:
        """Sum of all scoring dimensions."""
        return round(
            self.business_relevance
            + self.search_opportunity
            + self.aeo_fit
            + self.freshness
            + self.authority_to_win
            + self.uniqueness_vs_archive
            + self.production_ease,
            2,
        )


class ScoredTopic(BaseModel):
    """A topic candidate with its score and selection status."""

    candidate: TopicCandidate
    score: TopicScore
    rejection_reasons: list[str] = Field(default_factory=list)
    selected: bool = False
    judge_scores: list["JudgeScore"] = Field(default_factory=list)
    consensus_score: Optional[float] = Field(default=None, ge=0.0, le=10.0)
    consensus_variance: Optional[float] = Field(default=None, ge=0.0)
    selection_notes: list[str] = Field(default_factory=list)
    reuse_penalty: float = Field(default=0.0, ge=0.0, le=10.0)

    @computed_field
    @property
    def total_score(self) -> float:
        """Convenience accessor for the topic's total score."""
        return self.score.total


# ---------------------------------------------------------------------------
# Research brief
# ---------------------------------------------------------------------------


class OutlineSection(BaseModel):
    """A section in the article outline."""

    heading: str = Field(..., min_length=2)
    description: str = Field(..., min_length=5)
    target_word_count: int = Field(default=200, ge=50, le=1500)
    key_points: list[str] = Field(default_factory=list)


class FAQ(BaseModel):
    """A frequently asked question with suggested answer."""

    question: str = Field(..., min_length=10)
    suggested_answer: str = Field(..., min_length=20)


class InternalLink(BaseModel):
    """A suggested internal link to existing Macroscope content."""

    anchor_text: str
    target_path: str = Field(..., description="Relative URL path on macroscope.com")
    context: str = Field(..., description="Where/how to place this link in the article")


class ResearchBrief(BaseModel):
    """Comprehensive research brief for blog writing.

    Contains everything a writer needs to produce the article
    without additional research.
    """

    topic: TopicCandidate
    outline: list[OutlineSection] = Field(..., min_length=3)
    target_word_count: int = Field(default=2000, ge=800, le=5000)
    primary_keyword: str
    secondary_keywords: list[str] = Field(..., min_length=2)
    entities: list[str] = Field(..., min_length=1, description="People, companies, tools, concepts")
    faqs: list[FAQ] = Field(..., min_length=4)
    claims_needing_evidence: list[str]
    internal_link_suggestions: list[InternalLink]
    cta: str = Field(..., min_length=5)
    do_not_say: list[str] = Field(..., min_length=1)
    meta_description: str = Field(..., min_length=50, max_length=160)
    title_options: list[str] = Field(..., min_length=2)

    @field_validator("primary_keyword")
    @classmethod
    def keyword_normalized(cls, v: str) -> str:
        return v.lower().strip()

    def brief_hash(self) -> str:
        """SHA-256 prefix for traceability."""
        return hashlib.sha256(self.model_dump_json().encode()).hexdigest()[:12]


class BriefQualityReport(BaseModel):
    """Local evaluation of the generated research brief."""

    score: float = Field(..., ge=0.0, le=10.0)
    passed: bool
    notes: list[str] = Field(default_factory=list)


class BriefOutlinePlan(BaseModel):
    """Specialist output for outline and title planning."""

    outline: list[OutlineSection] = Field(..., min_length=3)
    target_word_count: int = Field(default=2000, ge=800, le=5000)
    title_options: list[str] = Field(..., min_length=2)


class BriefEntityPlan(BaseModel):
    """Specialist output for keyword and entity planning."""

    primary_keyword: str
    secondary_keywords: list[str] = Field(..., min_length=2)
    entities: list[str] = Field(..., min_length=1)
    meta_description: str = Field(..., min_length=50, max_length=160)


class BriefFAQPlan(BaseModel):
    """Specialist output for FAQ planning."""

    faqs: list[FAQ] = Field(..., min_length=4)


class BriefLinkPlan(BaseModel):
    """Specialist output for internal links and CTA."""

    internal_link_suggestions: list[InternalLink] = Field(..., min_length=2)
    cta: str = Field(..., min_length=5)


class BriefClaimsPlan(BaseModel):
    """Specialist output for evidence and risk guidance."""

    claims_needing_evidence: list[str] = Field(default_factory=list)
    do_not_say: list[str] = Field(..., min_length=1)


# ---------------------------------------------------------------------------
# Articles
# ---------------------------------------------------------------------------


class DraftArticle(BaseModel):
    """First draft of the blog article."""

    title: str
    slug: str = Field(..., pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
    content_md: str = Field(..., min_length=100)
    word_count: int = Field(..., ge=1)
    brief_hash: str = Field(..., description="SHA-256 prefix of the serialized brief")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class BlueprintSection(BaseModel):
    """A compact planned section for a writer blueprint."""

    heading: str = Field(..., min_length=2)
    bullets: list[str] = Field(default_factory=list)
    claims_to_support: list[str] = Field(default_factory=list)


class WriterBlueprint(BaseModel):
    """Low-token draft plan used before generating a full article."""

    writer_id: str
    writer_label: str
    focus_summary: str
    title: str
    opening_hook: str = Field(..., min_length=20)
    direct_answer: str = Field(..., min_length=30)
    sections: list[BlueprintSection] = Field(default_factory=list, min_length=3)
    faq_plan: list[str] = Field(default_factory=list)
    internal_link_targets: list[str] = Field(default_factory=list)
    claims_plan: list[str] = Field(default_factory=list)
    estimated_word_count: int = Field(default=1800, ge=600, le=5000)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class BlueprintEvaluation(BaseModel):
    """Local scoring for one writer blueprint."""

    writer_id: str
    score: float = Field(..., ge=0.0, le=10.0)
    notes: list[str] = Field(default_factory=list)


class DraftVariant(BaseModel):
    """One writer persona's candidate draft."""

    writer_id: str
    writer_label: str
    focus_summary: str
    title: str
    slug: str = Field(..., pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
    content_md: str = Field(..., min_length=100)
    word_count: int = Field(..., ge=1)
    brief_hash: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class JudgeScore(BaseModel):
    """Single judge score for a topic or article."""

    judge: str
    score: float = Field(..., ge=0.0, le=10.0)
    rationale: str = Field(..., min_length=5)
    notes: list[str] = Field(default_factory=list)


class DraftEvaluation(BaseModel):
    """Aggregated scores for one draft variant."""

    writer_id: str
    scores: list[JudgeScore] = Field(default_factory=list)
    average_score: float = Field(..., ge=0.0, le=10.0)
    min_score: float = Field(..., ge=0.0, le=10.0)
    score_variance: float = Field(default=0.0, ge=0.0, le=10.0)
    passed: bool
    notes: list[str] = Field(default_factory=list)


class FinalQualityGate(BaseModel):
    """Final publish gate result after optimization."""

    round_number: int = Field(..., ge=1)
    scores: list[JudgeScore] = Field(default_factory=list)
    average_score: float = Field(..., ge=0.0, le=10.0)
    min_score: float = Field(..., ge=0.0, le=10.0)
    score_variance: float = Field(default=0.0, ge=0.0, le=10.0)
    technical_accuracy_score: float = Field(..., ge=0.0, le=10.0)
    passed: bool
    notes: list[str] = Field(default_factory=list)


class SectionExcerpt(BaseModel):
    """Compact excerpt for one section in the article manifest."""

    heading: str
    excerpt: str
    word_count: int = Field(default=0, ge=0)


class ArticleManifest(BaseModel):
    """Compact article representation used by optimizers and judges."""

    title: str
    slug: str
    primary_keyword: str
    opening_direct_answer: str = ""
    heading_map: list[str] = Field(default_factory=list)
    faq_questions: list[str] = Field(default_factory=list)
    internal_links: list[str] = Field(default_factory=list)
    claim_candidates: list[str] = Field(default_factory=list)
    section_excerpts: list[SectionExcerpt] = Field(default_factory=list)
    qa_snapshot: dict[str, Any] = Field(default_factory=dict)
    seo_snapshot: dict[str, Any] = Field(default_factory=dict)
    word_count: int = Field(default=0, ge=0)
    meta_description: str = ""


class SectionRewrite(BaseModel):
    """Focused rewrite for one section heading."""

    heading: str
    markdown: str = Field(..., min_length=10)


class OptimizationPatch(BaseModel):
    """Structured patch plan returned by the optimizer coordinator."""

    opening_direct_answer: Optional[str] = None
    meta_description: Optional[str] = None
    internal_link_suggestions: list[InternalLink] = Field(default_factory=list)
    section_rewrites: list[SectionRewrite] = Field(default_factory=list)
    faq_questions_to_strengthen: list[str] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


class FactCheckReport(BaseModel):
    """Final fact-check result using live web research."""

    checked_claims: list[str] = Field(default_factory=list)
    verified_claims: list[str] = Field(default_factory=list)
    flagged_claims: list[str] = Field(default_factory=list)
    required_revisions: list[str] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)
    passed: bool = True


class SEOAEOScore(BaseModel):
    """SEO and AEO quality scores (each dimension 0-10, total 0-100)."""

    title_score: float = Field(..., ge=0.0, le=10.0)
    meta_description_score: float = Field(..., ge=0.0, le=10.0)
    keyword_density_score: float = Field(..., ge=0.0, le=10.0)
    heading_structure_score: float = Field(..., ge=0.0, le=10.0)
    internal_links_score: float = Field(..., ge=0.0, le=10.0)
    faq_presence_score: float = Field(..., ge=0.0, le=10.0)
    direct_answer_score: float = Field(..., ge=0.0, le=10.0)
    readability_score: float = Field(..., ge=0.0, le=10.0)
    content_depth_score: float = Field(..., ge=0.0, le=10.0)
    freshness_signals_score: float = Field(..., ge=0.0, le=10.0)

    @computed_field
    @property
    def total(self) -> float:
        """Sum of all SEO/AEO dimensions (0-100)."""
        return round(
            self.title_score
            + self.meta_description_score
            + self.keyword_density_score
            + self.heading_structure_score
            + self.internal_links_score
            + self.faq_presence_score
            + self.direct_answer_score
            + self.readability_score
            + self.content_depth_score
            + self.freshness_signals_score,
            2,
        )

    @computed_field
    @property
    def normalized(self) -> float:
        """Normalized score (0.0-1.0)."""
        return round(self.total / 100.0, 4)

    @computed_field
    @property
    def grade(self) -> str:
        """Letter grade: A (>=80), B (>=65), C (>=50), D (>=35), F (<35)."""
        t = self.total
        if t >= 80:
            return "A"
        if t >= 65:
            return "B"
        if t >= 50:
            return "C"
        if t >= 35:
            return "D"
        return "F"


class FinalArticle(BaseModel):
    """The final, QA-passed article ready for publishing."""

    title: str
    slug: str = Field(..., pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
    content_md: str = Field(..., min_length=100)
    meta_description: str = Field(..., min_length=50, max_length=160)
    word_count: int = Field(..., ge=1)
    seo_aeo_score: SEOAEOScore
    faqs_present: bool
    internal_links: list[str]
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SourceCoverageReport(BaseModel):
    """Coverage summary across research source classes."""

    counts_by_class: dict[str, int] = Field(default_factory=dict)
    missing_classes: list[str] = Field(default_factory=list)
    unique_classes: int = Field(default=0, ge=0)
    primary_technical_source_present: bool = False
    score: float = Field(default=0.0, ge=0.0, le=10.0)
    passed: bool = False
    notes: list[str] = Field(default_factory=list)


class ProviderCallUsage(BaseModel):
    """Token usage for one provider/model call."""

    stage: Optional[str] = None
    provider: str
    operation: str
    model: str
    input_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    total_tokens: int = Field(default=0, ge=0)
    web_search_used: bool = False
    cached: bool = False
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class StageUsageSummary(BaseModel):
    """Aggregated token usage for one pipeline stage."""

    stage: str
    call_count: int = Field(default=0, ge=0)
    input_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    total_tokens: int = Field(default=0, ge=0)
    web_search_calls: int = Field(default=0, ge=0)
    cached_calls: int = Field(default=0, ge=0)


class RunUsageLedger(BaseModel):
    """Per-call and per-stage token usage for a full run."""

    calls: list[ProviderCallUsage] = Field(default_factory=list)
    stage_summaries: list[StageUsageSummary] = Field(default_factory=list)

    @computed_field
    @property
    def total_input_tokens(self) -> int:
        return sum(call.input_tokens for call in self.calls)

    @computed_field
    @property
    def total_output_tokens(self) -> int:
        return sum(call.output_tokens for call in self.calls)

    @computed_field
    @property
    def total_tokens(self) -> int:
        return sum(call.total_tokens for call in self.calls)


class TopicCooldownRecord(BaseModel):
    """Cooldown state for a previously published topic."""

    slug: str
    title: str
    cluster: str
    published_at: str
    cooldown_until: str
    keywords: list[str] = Field(default_factory=list)


class TopicShortlistRecord(BaseModel):
    """Shortlisted topics that were not selected in a prior run."""

    slug: str
    title: str
    cluster: str
    recorded_at: str
    keywords: list[str] = Field(default_factory=list)
    run_id: str


class TopicReuseAssessment(BaseModel):
    """Eligibility and penalty result for reusing a topic angle."""

    slug: str
    eligible: bool = True
    penalty: float = Field(default=0.0, ge=0.0, le=10.0)
    reasons: list[str] = Field(default_factory=list)
    cooldown_until: Optional[str] = None


# ---------------------------------------------------------------------------
# Run tracking and resumable execution
# ---------------------------------------------------------------------------


class ExecutionState(BaseModel):
    """Durable execution state for one dashboard-triggered run."""

    run_id: str
    status: str = Field(
        default="running",
        pattern=r"^(running|stopping|interrupted|resumable|resuming|completed|failed|canceled)$",
    )
    current_stage: Optional[str] = None
    next_stage: Optional[str] = None
    completed_stages: list[str] = Field(default_factory=list)
    resume_stage: Optional[str] = None
    resume_count: int = Field(default=0, ge=0)
    worker_pid: Optional[int] = Field(default=None, ge=1)
    worker_create_time: Optional[float] = Field(default=None, ge=0.0)
    stop_requested: bool = False
    started_at: datetime
    last_heartbeat_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_error: Optional[str] = None
    resume_reason: Optional[str] = None


class StageCheckpoint(BaseModel):
    """Checkpoint captured after a stage completes successfully."""

    stage: str
    completed_at: datetime
    attempt: int = Field(default=1, ge=1)
    ctx_fragment: dict[str, Any] = Field(default_factory=dict)
    stage_result: dict[str, Any] = Field(default_factory=dict)


class ResumePlan(BaseModel):
    """Computed resume cursor for an interrupted run."""

    run_id: str
    resumable: bool = False
    resume_stage: Optional[str] = None
    completed_stages: list[str] = Field(default_factory=list)
    resume_count: int = Field(default=0, ge=0)
    resume_reason: Optional[str] = None
    ctx: dict[str, Any] = Field(default_factory=dict)
    resumed_from_stage: Optional[str] = None


class StageResult(BaseModel):
    """Result of a single pipeline stage execution."""

    stage: str
    success: bool
    duration_seconds: float = Field(..., ge=0.0)
    error: Optional[str] = None
    failure_category: Optional[FailureCategory] = None
    artifact_path: Optional[str] = None


class RunSummary(BaseModel):
    """Summary of a complete pipeline run."""

    run_id: str
    started_at: datetime
    completed_at: Optional[datetime] = None
    resume_count: int = Field(default=0, ge=0)
    resumed_from_stage: Optional[str] = None
    stages: list[StageResult] = Field(default_factory=list)
    topic_selected: Optional[str] = None
    final_score: Optional[float] = None
    final_grade: Optional[str] = None
    word_count: Optional[int] = None
    artifacts: dict[str, str] = Field(
        default_factory=dict, description="stage_name -> artifact file path"
    )
    errors: list[str] = Field(default_factory=list)

    @computed_field
    @property
    def success(self) -> bool:
        """Whether the run completed without errors."""
        return len(self.errors) == 0 and self.completed_at is not None

    @computed_field
    @property
    def total_duration_seconds(self) -> float:
        """Total wall-clock time of the run."""
        if self.started_at and self.completed_at:
            return round((self.completed_at - self.started_at).total_seconds(), 2)
        return sum(s.duration_seconds for s in self.stages)

    @computed_field
    @property
    def stages_completed(self) -> list[str]:
        """Names of stages that completed successfully."""
        return [s.stage for s in self.stages if s.success]

    @computed_field
    @property
    def stages_failed(self) -> list[str]:
        """Names of stages that failed."""
        return [s.stage for s in self.stages if not s.success]

    def to_concise_json(self) -> dict:
        """Return a CI-friendly concise summary dict."""
        return {
            "run_id": self.run_id,
            "success": self.success,
            "topic": self.topic_selected,
            "score": self.final_score,
            "grade": self.final_grade,
            "word_count": self.word_count,
            "duration_seconds": self.total_duration_seconds,
            "resume_count": self.resume_count,
            "resumed_from_stage": self.resumed_from_stage,
            "stages_completed": self.stages_completed,
            "stages_failed": self.stages_failed,
            "error_count": len(self.errors),
            "errors": self.errors[:5],
        }
